2025-03-05 21:32:20,567 INFO    MainThread:11332 [wandb_setup.py:_flush():76] Current SDK version is 0.17.3
2025-03-05 21:32:20,567 INFO    MainThread:11332 [wandb_setup.py:_flush():76] Configure stats pid to 11332
2025-03-05 21:32:20,567 INFO    MainThread:11332 [wandb_setup.py:_flush():76] Loading settings from /Users/nilaygaitonde/.config/wandb/settings
2025-03-05 21:32:20,567 INFO    MainThread:11332 [wandb_setup.py:_flush():76] Loading settings from /Users/nilaygaitonde/Documents/Projects/cv_project/wandb/settings
2025-03-05 21:32:20,567 INFO    MainThread:11332 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-03-05 21:32:20,567 INFO    MainThread:11332 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'face-detection.py', 'program_abspath': '/Users/nilaygaitonde/Documents/Projects/cv_project/face-detection.py', 'program': '/Users/nilaygaitonde/Documents/Projects/cv_project/face-detection.py'}
2025-03-05 21:32:20,567 INFO    MainThread:11332 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-03-05 21:32:20,567 INFO    MainThread:11332 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-03-05 21:32:20,567 INFO    MainThread:11332 [wandb_init.py:_log_setup():520] Logging user logs to /Users/nilaygaitonde/Documents/Projects/cv_project/wandb/run-20250305_213220-advshw28/logs/debug.log
2025-03-05 21:32:20,568 INFO    MainThread:11332 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/nilaygaitonde/Documents/Projects/cv_project/wandb/run-20250305_213220-advshw28/logs/debug-internal.log
2025-03-05 21:32:20,568 INFO    MainThread:11332 [wandb_init.py:init():560] calling init triggers
2025-03-05 21:32:20,570 INFO    MainThread:11332 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'epochs': 10, 'lr': 0.001, 'patience': 5, 'min_delta': 0, 'batch_size': 20}
2025-03-05 21:32:20,570 INFO    MainThread:11332 [wandb_init.py:init():610] starting backend
2025-03-05 21:32:20,570 INFO    MainThread:11332 [wandb_init.py:init():614] setting up manager
2025-03-05 21:32:20,572 INFO    MainThread:11332 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-03-05 21:32:20,580 INFO    MainThread:11332 [wandb_init.py:init():622] backend started and connected
2025-03-05 21:32:20,652 INFO    MainThread:11332 [wandb_init.py:init():711] updated telemetry
2025-03-05 21:32:20,653 INFO    MainThread:11332 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2025-03-05 21:32:21,452 INFO    MainThread:11332 [wandb_run.py:_on_init():2402] communicating current version
2025-03-05 21:32:21,597 INFO    MainThread:11332 [wandb_run.py:_on_init():2411] got version response upgrade_message: "wandb version 0.19.8 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-03-05 21:32:21,598 INFO    MainThread:11332 [wandb_init.py:init():795] starting run threads in backend
2025-03-05 21:32:22,885 WARNING MainThread:11332 [wandb_init.py:init():1175] interrupted
Traceback (most recent call last):
  File "/Users/nilaygaitonde/anaconda3/envs/deeplearning/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/nilaygaitonde/anaconda3/envs/deeplearning/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nilaygaitonde/anaconda3/envs/deeplearning/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nilaygaitonde/anaconda3/envs/deeplearning/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nilaygaitonde/anaconda3/envs/deeplearning/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nilaygaitonde/anaconda3/envs/deeplearning/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nilaygaitonde/anaconda3/envs/deeplearning/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-03-05 21:32:42,569 WARNING MsgRouterThr:11332 [router.py:message_loop():77] message_loop has been closed
